---
title: "Module2_Exercise3"
author: "Laura Huber"
date: "May 16, 2019"
output: html_document
---
EXERCISE ESTIMATION

## Estimating R0
```{r load data}
load('data (2).RData')     #load the data and plot flu cases
plot(flu,type='b',log='y',main='Epidemic in a British boarding school', cex.main=0.85,
 xlab='Day', ylab='Active influenza cases')
```
### Exercise 1: Estimating R0 from the final outbreak size

```{r R0 function}
p <- seq(0,1,0.0001)

r0 <- log(1-p)/(-p)
plot(p, r0)

```

## Linear approximation

```{r}
model<-lm(log(flu[1:4])~day[1:4],data=flu);  #fit a linear model
summary(model)         #summary statistics for fit model
slope<-coef(model)[2]  #extract slope parameter
slope                 #print to screen
```

### Exercise 2
```{r}
gamma <- 0.4
duration <- 1/gamma
observed.duration <- 1
est.gamma <- 1/observed.duration
est.gamma

slope+1
slope/2+1
```

### Exercise 3

```{r}
niamey[5,3]<-0  #replace a "NA"
niamey<-data.frame(biweek=rep(seq(1,16),3),site=c(rep(1,16),rep(2,16),rep(3,16)),
                   cases=c(niamey[,1],niamey[,2],niamey[,3])) #define "biweeks"



```


```{r}
model2<-lm(log(cases)~(biweek),data=niamey[1:9,]);  #fit a linear model
summary(model2)         #summary statistics for fit model
slope2<-coef(model2)[2]  #extract slope parameter
slope2                 #print to screen
```

### Exercise 4

```{r}
R0funtion <- function(.n){
  numberOfDatapoints <- niamey[niamey$site==1 & niamey$biweek<.n,]
  
  models<-lm(log(cases)~(biweek),data=numberOfDatapoints);  
slopes<-coef(models)[2] 
slopes/(1/(14/365))+1
}
ns <-3:11
r0 <- c()
for(i in 1:length(ns)){
  r0[i] <- R0funtion(.n=ns[i])
}

plot(x=(ns-1), y=r0)

```  
 

```{r}

plot(niamey$biweek,niamey$cases,type='p',col=niamey$site,xlab='Biweek',ylab='Cases')
lines(niamey$biweek[niamey$site==1],niamey$cases[niamey$site==1])
lines(niamey$biweek[niamey$site==2],niamey$cases[niamey$site==2],col=2)
lines(niamey$biweek[niamey$site==3],niamey$cases[niamey$site==3],col=3)
```
### Exercise 5
##Dynamical Model
```{r}
closed.sir.model <- function (t, x, params) {  #SIR model equations
  S <- x[1]
  I <- x[2]
  beta <- params[1]
  gamma <- params[2]
  dS <- -beta*S*I
  dI <- beta*S*I-(gamma)*I
  list(c(dS,dI))
}
```


## Objective function

```{r}
sse.sir <- function(params0,data,site){  #function to calculate squared errors
  data<-data[data$site==site,]    #working dataset, based on site
  t <- data[,1]*14/365            #time in biweeks
  cases <- data[,3]               #number of cases
  beta <- exp(params0[1])            #parameter beta
  S0 <- exp(params0[2])           #initial susceptibles
  I0 <- exp(params0[3])
  gamma <- exp(params0[4])
  out <- as.data.frame(ode(c(S=S0,I=I0),times=t,closed.sir.model,parms=c(beta,gamma),hmax=1/120))
  sse<-sum((out$I-cases)^2)       #sum of squared errors
}
```

## Optimization
```{r}

library(deSolve)   #differential equation library
params0<-c(-3.2,7.3,-2.6,-4.0)  #initial guess

fit1 <- optim(params0,sse.sir,data=niamey,site=1) #fit
exp(fit1$par)  #back-transform parameters
fit2 <- optim(params0,sse.sir,data=niamey,site=2) #fit
exp(fit2$par)  #back-transform parameters
fit3 <- optim(params0,sse.sir,data=niamey,site=3) #fit
exp(fit3$par)  #back-transform parameters


par(mfrow=c(3,1))   #set up plotting area for multiple panels
plot(cases~biweek,data=subset(niamey,site==1),type='b',col='blue', pch=21) #plot site 1
t <- subset(niamey,site==1)[,1]*14/365
mod.pred<-as.data.frame(ode(c(S=exp(fit1$par[2]),I=exp(fit1$par[3])),times=t,
                              closed.sir.model,parms=c(exp(fit1$par[1]),exp(fit1$par[4])),hmax=1/120))
                              #obtain model predictions
lines(mod.pred$I~subset(niamey,site==1)[,1]) #and plot as a line

plot(cases~biweek,data=subset(niamey,site==2),type='b',col=site) #site 2
t <- subset(niamey,site==2)[,1]*14/365
mod.pred<-as.data.frame(ode(c(S=exp(fit2$par[2]),I=exp(fit2$par[3])),times=t,
                              closed.sir.model,parms=c(exp(fit2$par[1]),exp(fit2$par[4])),hmax=1/120))
lines(mod.pred$I~subset(niamey,site==2)[,1])


plot(cases~biweek,data=subset(niamey,site==3),type='b',col=site) #site 3
t <- subset(niamey,site==3)[,1]*14/365
mod.pred<-as.data.frame(ode(c(S=exp(fit3$par[2]),I=exp(fit3$par[3])),times=t,
                              closed.sir.model,parms=c(exp(fit3$par[1]),exp(fit3$par[4])),hmax=1/120))
lines(mod.pred$I~subset(niamey,site==3)[,1])
```

### Exercise 6
```{r}
closed.sir.model <- function (t, x, params) {  #SIR model equations
  S <- x[1]
  I <- x[2]
  beta <- params[1]
  gamma <- params[2]
  dS <- -beta*S*I
  dI <- beta*S*I-(gamma)*I
  list(c(dS,dI))
}
```



```{r}
sse.sir <- function(params0,data,site){  #function to calculate squared errors
  data<-data[data$site==site,]    #working dataset, based on site
  t <- data[,1]*14/365            #time in biweeks
  cases <- data[,3]               #number of cases
  beta <- exp(params0[1])            #parameter beta
  S0 <- exp(params0[2])           #initial susceptibles
 I0 <- 1.0
  gamma <- exp(params0[3])
  out <- as.data.frame(ode(c(S=S0,I=I0),times=t,closed.sir.model,parms=c(beta,gamma),hmax=1/120))
  sse<-sum((out$I-cases)^2)       #sum of squared errors
}
```

```{r}

library(deSolve)   #differential equation library
params0<-c(-3.2,-2.6,-4.0)  #initial guess

fit1 <- optim(params0,sse.sir,data=niamey,site=1) #fit
exp(fit1$par)  #back-transform parameters
fit2 <- optim(params0,sse.sir,data=niamey,site=2) #fit
exp(fit2$par)  #back-transform parameters
fit3 <- optim(params0,sse.sir,data=niamey,site=3) #fit
exp(fit3$par)  #back-transform parameters


par(mfrow=c(3,1))   #set up plotting area for multiple panels
plot(cases~biweek,data=subset(niamey,site==1),type='b',col='blue', pch=21) #plot site 1
t <- subset(niamey,site==1)[,1]*14/365
mod.pred<-as.data.frame(ode(c(S=exp(fit1$par[2]),I=1.0),times=t,
                              closed.sir.model,parms=c(exp(fit1$par[1]),1.0),hmax=1/120))
                              #obtain model predictions
lines(mod.pred$I~subset(niamey,site==1)[,1]) #and plot as a line

plot(cases~biweek,data=subset(niamey,site==2),type='b',col=site) #site 2
t <- subset(niamey,site==2)[,1]*14/365
mod.pred<-as.data.frame(ode(c(S=exp(fit2$par[2]),I=1.0),times=t,
                              closed.sir.model,parms=c(exp(fit2$par[1]),1.0),hmax=1/120))
lines(mod.pred$I~subset(niamey,site==2)[,1])


plot(cases~biweek,data=subset(niamey,site==3),type='b',col=site) #site 3
t <- subset(niamey,site==3)[,1]*14/365
mod.pred<-as.data.frame(ode(c(S=exp(fit3$par[2]),I=1.0),times=t,
                              closed.sir.model,parms=c(exp(fit3$par[1]),1.0),hmax=1/120))
lines(mod.pred$I~subset(niamey,site==3)[,1])
```

